/*
Enter your query here.
*/

SSELECT
    IF (GRADES.GRADE < 8, CONCAT('NULL'), STUDENTS.NAME),
    GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS
JOIN GRADES
ON STUDENTS.MARKS >= GRADES.MIN_MARK AND STUDENTS.MARKS <= GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME ASC, STUDENTS.MARKS ASC
